name: NPM Test

on:
  push:
    branches:
      - main # Change to your default branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: <path_to_your_test_results_directory>
